"""Adding proxies

Revision ID: 027e663a2ef7
Revises: be6e418256ea
Create Date: 2022-12-18 23:40:51.706072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027e663a2ef7'
down_revision = 'be6e418256ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
