"""initial revision

Revision ID: 32ff1ab4363a
Revises: 
Create Date: 2023-05-06 10:19:35.033070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ff1ab4363a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('dork_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dork_authors_id'), 'dork_authors', ['id'], unique=False)
    op.create_table('dork_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dork_categories_id'), 'dork_categories', ['id'], unique=False)
    op.create_table('google_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_search_id'), 'google_search', ['id'], unique=False)
    op.create_table('proxy_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_type_id'), 'proxy_type', ['id'], unique=False)
    op.create_table('google_dorks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dork', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dork_authors.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['dork_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_dorks_id'), 'google_dorks', ['id'], unique=False)
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('proxy_type_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proxy_type_id'], ['proxy_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_google_dorks_id'), table_name='google_dorks')
    op.drop_table('google_dorks')
    op.drop_index(op.f('ix_proxy_type_id'), table_name='proxy_type')
    op.drop_table('proxy_type')
    op.drop_index(op.f('ix_google_search_id'), table_name='google_search')
    op.drop_table('google_search')
    op.drop_index(op.f('ix_dork_categories_id'), table_name='dork_categories')
    op.drop_table('dork_categories')
    op.drop_index(op.f('ix_dork_authors_id'), table_name='dork_authors')
    op.drop_table('dork_authors')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
