"""Adding dorks

Revision ID: 437ac59e7240
Revises: 715f2202608b
Create Date: 2022-12-19 00:01:08.444385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437ac59e7240'
down_revision = '715f2202608b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
