"""adding search and cases

Revision ID: 5f81186d09a3
Revises: c1fa3a95b083
Create Date: 2022-12-21 17:47:27.577898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f81186d09a3'
down_revision = 'c1fa3a95b083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
