"""Adding created

Revision ID: 715f2202608b
Revises: 027e663a2ef7
Create Date: 2022-12-18 23:43:05.661698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715f2202608b'
down_revision = '027e663a2ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('proxy_type_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proxy_type_id'], ['proxy_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_table('proxies')
    # ### end Alembic commands ###
