"""migrate

Revision ID: d51c30bacade
Revises: 964597ac2699
Create Date: 2023-10-21 22:17:19.877075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd51c30bacade'
down_revision = '964597ac2699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('machine', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_machines_id'), 'scan_machines', ['id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.add_column('entities', sa.Column('last_edited', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('entities', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_seen')
    op.drop_column('projects', 'is_favorite')
    op.drop_column('entities', 'is_favorite')
    op.drop_column('entities', 'last_edited')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_machines_id'), table_name='scan_machines')
    op.drop_table('scan_machines')
    # ### end Alembic commands ###
