#!/usr/bin/env bash

export_container_ids() {
    export ID_OB_UI=$(cmd/container_id "ui");
    export ID_OB_BACKEND=$(cmd/container_id "backend");
    export ID_OB_REDIS=$(cmd/container_id "redis");
    export ID_OB_DB=$(cmd/container_id "db");
    export ID_OB_JANUS=$(cmd/container_id "janus");
    export ID_OB_SDB=$(cmd/container_id "sdb");
    export ID_OB_INDEX=$(cmd/container_id "index");
    export ID_OB_WORKER=$(cmd/container_id "worker");
    export ID_OB_CLEARLY=$(cmd/container_id "clearly");
    export ID_OB_S3=$(cmd/container_id "s3");
}

export_container_ids