#!/usr/bin/env bash
. ./cmd/env

run_restart() {
    if [ ! -z "$OB_CMD" ] & [ ! -z "$OB_CMD_ARGS" ]; then
        ob_compose restart $OB_CMD_ARGS;
        exit 0
    else
        ob_compose restart;
        exit 0
    fi
}

run_restart
