"""Modified search_category relationships

Revision ID: 0c2bc3667e16
Revises: 87768a5b0d31
Create Date: 2021-08-28 18:29:20.964879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2bc3667e16'
down_revision = '87768a5b0d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cse_search_category_id_fkey', 'cse', type_='foreignkey')
    op.drop_column('cse', 'search_category_id')
    op.drop_constraint('search_search_category_id_fkey', 'search', type_='foreignkey')
    op.drop_column('search', 'search_category_id')
    op.add_column('search_category', sa.Column('search_id', sa.Integer(), nullable=True))
    op.add_column('search_category', sa.Column('cse_id', sa.Integer(), nullable=True))
    op.drop_index('ix_search_category_id', table_name='search_category')
    op.drop_index('ix_search_category_name', table_name='search_category')
    op.create_foreign_key(None, 'search_category', 'cse', ['cse_id'], ['id'])
    op.create_foreign_key(None, 'search_category', 'search', ['search_id'], ['id'])
    op.drop_column('search_category', 'id')
    op.drop_column('search_category', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_category', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_category', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'search_category', type_='foreignkey')
    op.drop_constraint(None, 'search_category', type_='foreignkey')
    op.create_index('ix_search_category_name', 'search_category', ['name'], unique=False)
    op.create_index('ix_search_category_id', 'search_category', ['id'], unique=False)
    op.drop_column('search_category', 'cse_id')
    op.drop_column('search_category', 'search_id')
    op.add_column('search', sa.Column('search_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('search_search_category_id_fkey', 'search', 'search_category', ['search_category_id'], ['id'])
    op.add_column('cse', sa.Column('search_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cse_search_category_id_fkey', 'cse', 'search_category', ['search_category_id'], ['id'])
    # ### end Alembic commands ###
