"""Updated projects table

Revision ID: 171be48dfded
Revises: ed6b96dc83f8
Create Date: 2021-08-26 21:32:17.556414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171be48dfded'
down_revision = 'ed6b96dc83f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
