"""Modified search and search_category

Revision ID: 22b7eeb42a31
Revises: a13bfde2b847
Create Date: 2021-08-28 05:23:58.980469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b7eeb42a31'
down_revision = 'a13bfde2b847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('search_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'search', 'search_category', ['search_category_id'], ['id'])
    op.drop_constraint('search_category_search_fkey', 'search_category', type_='foreignkey')
    op.drop_column('search_category', 'search')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_category', sa.Column('search', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('search_category_search_fkey', 'search_category', 'search', ['search'], ['id'])
    op.drop_constraint(None, 'search', type_='foreignkey')
    op.drop_column('search', 'search_category_id')
    # ### end Alembic commands ###
