"""initial revision

Revision ID: 562c7c76009c
Revises: d2a32f973195
Create Date: 2021-09-20 20:44:30.053418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562c7c76009c'
down_revision = 'd2a32f973195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
