"""modified search table

Revision ID: 5f5849b87f6f
Revises: bb9bda22ff51
Create Date: 2021-09-19 21:22:06.383294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f5849b87f6f'
down_revision = 'bb9bda22ff51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_result', 'thumbnail_width')
    op.drop_column('search_result', 'breadcrumb_url')
    op.drop_column('search_result', 'created')
    op.drop_column('search_result', 'thumbnail_url')
    op.drop_column('search_result', 'file_format')
    op.drop_column('search_result', 'thumbnail_height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_result', sa.Column('thumbnail_height', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_result', sa.Column('file_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_result', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_result', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('search_result', sa.Column('breadcrumb_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('search_result', sa.Column('thumbnail_width', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
