"""Updated tables

Revision ID: 6c70106c9290
Revises: ac907f23a402
Create Date: 2021-08-26 21:49:39.885127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c70106c9290'
down_revision = 'ac907f23a402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
