"""Updated projects table

Revision ID: 779e95ccddba
Revises: c92f1b6721c3
Create Date: 2021-08-26 18:45:42.237338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779e95ccddba'
down_revision = 'c92f1b6721c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
