"""Modified search_category and user

Revision ID: 87768a5b0d31
Revises: 22b7eeb42a31
Create Date: 2021-08-28 17:54:12.526401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87768a5b0d31'
down_revision = '22b7eeb42a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
