"""Updated projects table

Revision ID: ac907f23a402
Revises: 171be48dfded
Create Date: 2021-08-26 21:35:32.420800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac907f23a402'
down_revision = '171be48dfded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_description', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_description', 'project', ['description'], unique=False)
    # ### end Alembic commands ###
