"""changed search table

Revision ID: af812b041e08
Revises: f268e5f77979
Create Date: 2021-09-19 16:29:15.547874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af812b041e08'
down_revision = 'f268e5f77979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
