"""changed column name on search

Revision ID: bb9bda22ff51
Revises: 03febfa4433c
Create Date: 2021-09-19 16:45:45.866969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9bda22ff51'
down_revision = '03febfa4433c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('search', 'last_queried')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('last_queried', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('search', 'created')
    # ### end Alembic commands ###
