"""Added projects table

Revision ID: da77e8cced53
Revises: 36b67348231c
Create Date: 2021-08-26 18:35:42.818045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da77e8cced53'
down_revision = '36b67348231c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
