"""updated search table

Revision ID: e62ab1d0ba43
Revises: 5f5849b87f6f
Create Date: 2021-09-19 21:24:34.899211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62ab1d0ba43'
down_revision = '5f5849b87f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'last_updated')
    # ### end Alembic commands ###
