"""Modified search_category relationships

Revision ID: f268e5f77979
Revises: 0c2bc3667e16
Create Date: 2021-08-28 18:35:10.332686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f268e5f77979'
down_revision = '0c2bc3667e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
