"""changed last_queried on search table

Revision ID: f7c4067ff5b3
Revises: af812b041e08
Create Date: 2021-09-19 16:38:23.293089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c4067ff5b3'
down_revision = 'af812b041e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
